---
- hosts: all
  remote_user: k8s
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Copy nettest server service yaml
      become_user: root
      become_method: sudo
      become: yes
      copy:
        src: /mnt/c/Users/Ali/PycharmProjects/dissertation/kubernetes/deployments/nettest-server-service.yaml
        dest: /tmp/nettest-server-service.yaml
        owner: k8s
        group: root
        mode: '0777'
      register: server_yaml_copied
    - name: Copy network policy
      when: server_yaml_copied is succeeded
      become_user: root
      become_method: sudo
      become: yes
      copy:
        src: /mnt/c/Users/Ali/PycharmProjects/dissertation/kubernetes/network-policy/allow-all.yaml
        dest: /tmp/allow-all.yaml
        owner: k8s
        group: root
        mode: '0777'
      register: policy_copied
    - name: Initialise nettest server service and network policy
      when: policy_copied is succeeded
      become_user: k8s
      become_method: sudo
      become: yes
      command: "{{ item }}"
      with_items:
         - kubectl apply -f /tmp/allow-all.yaml
         - kubectl apply -f /tmp/nettest-server-service.yaml
    - name: Wait for  nettest-server pod to initialise
      become: yes
      become_user: k8s
      become_method: sudo
      shell: "kubectl wait --for=condition=Ready pods --selector app=nettest-server --timeout=30s"
    - name: Save nettest-server service IP
      become_user: k8s
      become_method: sudo
      become: yes
      shell: " kubectl describe pods --selector app=nettest-server | grep Node:  | awk '{print $2}' | cut -d '/' -f2"
      register: SERVER_IP
    - debug:
        msg: "{{ SERVER_IP.stdout }}"
    - local_action: copy content={{ SERVER_IP.stdout }} dest=/mnt/c/Users/Ali/PycharmProjects/dissertation/bash/serverip.txt
