---
- hosts: all
  remote_user: k8s
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  vars:
    pod_cidr: "10.100.0.0/24"
    service_cidr: "10.110.0.0/24"

  tasks:
    - name: Reset cluster
      shell: "kubeadm reset --force"
      register: reset_cluster

    - name: Initialise cluster
      when: reset_cluster is succeeded
      shell: |
        kubeadm init --service-cidr {{ service_cidr }} \
                     --pod-network-cidr {{ pod_cidr }} \
                     --apiserver-advertise-address {{ cluster_master_internal_ip }}

    - name: Create k8s config folder in home directory
      become_user: k8s
      become_method: sudo
      become: yes
      file:
        path: /home/{{ ansible_ssh_user }}/.kube
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: 0755
      register: create_folder

    - name: Copy config to non-root user folder
      when: create_folder is succeeded
      become_user: root
      become_method: sudo
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_ssh_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: '0644'


