---
- hosts: all
  remote_user: k8s
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: turn off swap
      command: swapoff -a

    - name: Remove swap fstab entry
      lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent

    - name: Installing prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - vim
          - software-properties-common
        state: present

    - name: Configure sysctl to disable reverse path filtering and enable ip forwarding
      shell:
        cmd: |
          modprobe overlay
          modprobe br_netfilter

          tee /etc/sysctl.d/kubernetes.conf<<EOF
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.ipv4.conf.all.rp_filter = 0
          EOF

          sysctl --system

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker
        mode: 0600

    - name: Install docker
      apt:
        name:
          - docker-ce=5:18.09.9~3-0~ubuntu-xenial
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable docker service
      service:
        name: docker
        enabled: yes

    - name: Add Google's GPG Key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add k8s repositories
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        mode: 0600

    - name: Install k8s components
      apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: latest
    - name: set kubernetes cgroup driver to systemd
      lineinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        line: 'Environment="KUBELET_EXTRA_ARGS=--cgroup-driver=systemd"'
    - name: set docker cgroup driver to systemd
      lineinfile:
        path: /etc/docker/daemon.json
        line: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"]
          }
        create: yes


    - name: Restart docker
      shell: "service docker restart"

    - name: Enable kubelet service
      service:
        name: kubelet
        enabled: yes

    - name: Reboot
      reboot:
        post_reboot_delay: 15
        connect_timeout: 60
        reboot_timeout: 60
        test_command: uptime
...