---
- hosts: all
  remote_user: k8s
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Configure sysctl to disable reverse path filtering and enable ip forwarding
      shell:
        cmd: |
            kubeadm reset --force
            sudo systemctl stop kubelet
            sudo systemctl stop docker
            sudo rm -rf /var/lib/cni/
            sudo rm -rf /var/lib/kubelet/
            sudo rm -rf /etc/cni/
            sudo rm -rf /var/lib/etcd/
            sudo rm -rf /var/etcd/
            sudo iptables -F
            modprobe -r ipip

    - name: Reboot
      reboot:
        post_reboot_delay: 15
        connect_timeout: 120
        reboot_timeout: 120
        test_command: uptime
...