apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettest-server-deployment
  labels:
    app: nettest-server
spec:
  selector:
    matchLabels:
      app: nettest-server
  template:
    metadata:
      labels:
        app: nettest-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nettest-server
                      - nettest-client
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nettest-server
        image: alimehrabikoshki/nettest-server:v4
        imagePullPolicy: Always
        args: ['-s']
        ports:
        - containerPort: 5201
          name: iperf-port
          protocol: TCP
        - containerPort: 80
          name: iperf-udp-port
          protocol: TCP
        - containerPort: 80
          name: httpd-port
          protocol: UDP
      restartPolicy: Always
      terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Service
metadata:
  name: nettest-server
spec:
  selector:
    app: nettest-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 5201
    nodePort: 5201
    targetPort: iperf-port
  - protocol: UDP
    port: 5201
    nodePort: 5201
    targetPort: iperf-udp-port
  - protocol: TCP
    port: 80
    nodePort: 80
    targetPort: httpd-port